<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageOutputPath>$(SolutionDir)Packages/</PackageOutputPath>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    </PropertyGroup>
    <Import Project="$(NuGetPackageRoot)net4x.nugetutility/$(NuGetUtilityVersion)/build/NuGet.Utility.props" Condition="Exists('$(NuGetPackageRoot)net4x.nugetutility/$(NuGetUtilityVersion)/build/NuGet.Utility.props')" />
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Net4x.$(MSBuildProjectName)</PackageId>
        <SignAssembly>true</SignAssembly>
        <DelaySign>false</DelaySign>
        <AssemblyOriginatorKeyFile>..\AsyncBridgeKey.snk</AssemblyOriginatorKeyFile>
        <NoWarn>NU5118</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
        <PackageReference Include="Net4x.NuGetUtility" Version="$(NuGetUtilityVersion)" PrivateAssets="All" />
        <PackageReference Include="Net4x.StandardTypesWrappers" Version="$(WrapperGeneratorVersion).$(VersionBuildSuffix)" />
    </ItemGroup>
    <ItemGroup>
        <None Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
    </ItemGroup>
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
    </ItemGroup>
    <Import Project="$(NuGetPackageRoot)net4x.nugetutility/$(NuGetUtilityVersion)/build/NuGet.Utility.targets" Condition="Exists('$(NuGetPackageRoot)net4x.nugetutility/$(NuGetUtilityVersion)/build/NuGet.Utility.targets')" />
</Project>