<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageOutputPath>$(SolutionDir)Packages/</PackageOutputPath>
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
        <Version>$(VersionPrefix).$(VersionSuffix)</Version>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Net4x.MsTests" Version="$(Net4xMsTestsVersion).$(VersionBuildSuffix)" />
        <PackageReference Include="Net4x.NuGetUtility" Version="$(NuGetUtilityVersion)" PrivateAssets="All" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>
    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
        <None Include="README.md" Link="README.md" Pack="true" PackagePath="\README.md" />
    </ItemGroup>
</Project>